kind: Service
apiVersion: v1
metadata:
  name: boot-backend
spec:
  selector:
    app: boot-backend
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-backend
spec:
  selector:
    matchLabels:
      app: boot-backend
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: boot-backend
        tier: backend
    spec:
      containers:
        - name: boot-backend
          image: boot-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

