kind: Service
apiVersion: v1
metadata:
  name: boot-frontend
spec:
  selector:
    app: boot-frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 8081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-frontend
spec:
  selector:
    matchLabels:
      app: boot-frontend
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: boot-frontend
        tier: frontend
    spec:
      containers:
        - name: boot-frontend
          image: harbor.lab.khadilkar.net:443/ykhadilkar/boot-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
