---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springboot/ci-base-8-jdk

inputs:
  - name: spring-boot-kubernetes

run:
  path: spring-boot-kubernetes/boot-backend/src/main/ci/build.sh
