resource_types:
  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.14"

resources:
  - name: spring-boot-kubernetes
    type: git
    source:
      uri: https://github.com/ykhadilkar/spring-boot-kubernetes.git
  - name: boot-backend-image
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/boot-backend
  - name: kubernetes-lab
    type: kubernetes
    source:
      server: https://cluster0.pks.lab.khadilkar.net:8443
      namespace: default
      insecure_skip_tls_verify: true
      token: ((kubernetes-lab-token))

jobs:
  - name: publish
    public: true
    serial: true
    plan:
      - get: spring-boot-kubernetes
      - task: build
        file: spring-boot-kubernetes/boot-backend/src/main/ci/build.yaml
      - put: boot-backend-image
        params:
          build: spring-boot-kubernetes/boot-backend
  - name: kubernetes-deploy-lab
    plan:
      - get: spring-boot-kubernetes
      - get: boot-backend-image
        trigger: true
        passed: [publish]
      - put: kubernetes-lab
        params:
          kubectl: apply -f spring-boot-kubernetes/boot-backend/boot-backend.yaml
          wait_until_ready_selector: app=boot-backend
